services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - network_1
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  inputter:
    image: inputter
    build: 
      context: ./
      dockerfile: ./inputter/Dockerfile
    networks:
      - network_1
    stdin_open: true
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  worker:
    image: worker
    deploy:
      mode: replicated
      replicas: 3
    build: 
      context: ./
      dockerfile: ./worker/Dockerfile
    networks:
      - network_1
    stdin_open: true
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

  outputter:
    image: outputter
    build: 
      context: ./
      dockerfile: ./outputter/Dockerfile
    networks:
      - network_1
    stdin_open: true
    tty: true
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true

networks:
  network_1:
    driver: overlay
    attachable: true